#!/usr/bin/env python3
# pyre-strict
# Copyright (c) Meta Platforms, Inc. and affiliates.

from typing import Any

class FlightRecorderHook:
    """Hook for tracking collective operations in flight."""

    def __init__(self, max_entries: int = ..., isolated: bool = ...) -> None: ...
    def register_with_comm(self, comm: Any) -> None: ...
    def unregister(self) -> None: ...
    def dump_json(self, include_completed: bool = ...) -> str: ...
    def dump_file(self, rank: int, include_completed: bool = ...) -> str: ...
    def reset(self) -> None: ...
    def is_enabled(self) -> bool: ...
    def size(self) -> int: ...
