variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: systemsRepoRef
  type: string
  default: refs/heads/develop
- name: systemsSparseCheckoutDir
  type: string
  default: 'projects/rocprofiler-sdk'
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}
  - repository: systems_repo
    type: github
    endpoint: ROCm
    name: ROCm/rocm-systems
    ref: ${{ parameters.systemsRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
    - mainline
  paths:
    exclude:
    - .github
    - .jenkins
    - docs
    - '.*.y*ml'
    - '*.md'
    - LICENSE.txt
    - NOTICES.txt

pr:
  autoCancel: true
  branches:
    include:
    - develop
    - mainline
  paths:
    exclude:
    - .github
    - .jenkins
    - docs
    - '.*.y*ml'
    - '*.md'
    - LICENSE.txt
    - NOTICES.txt
  drafts: false

stages:
- stage: rccl
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rccl.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: ''
      systemsRepo: systems_repo
      systemsSparseCheckoutDir: ${{ parameters.systemsSparseCheckoutDir }}
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
